name: build-docker
on: workflow_dispatch

jobs:
  docker-image-cpu:
    runs-on: ubuntu-22.04
    if: contains(github.ref, 'v2.')
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta cpu
        id: meta_cpu
        uses: docker/metadata-action@v4
        with:
          images: danielholland414/dev-env
          flavor: |
            latest=true
            suffix=-cpu
          tags: |
            type=raw,value=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          file: Dockerfile
          tags: ${{ steps.meta_cpu.outputs.tags }}
          # build-args: |
          #   SERVER_VERSION=${{ env.SERVER_VERSION }}
